import { Brain, CircuitBoard, Info, Sparkles } from 'lucide-react'

/**
 * The security narrative.
 *
 * The header states plainly which engine produced the text. When the LLM is
 * unavailable the panel says so and labels the content as rule-based — the
 * product never presents a deterministic fallback as an AI analysis.
 */
export default function AIExplanation({ explanation }) {
  if (!explanation) return null

  const isLlm = explanation.source === 'llm'
  const paragraphs = explanation.text.split(/\n{2,}/).filter(Boolean)

  return (
    <section className="mt-8 animate-fade-up">
      <div
        className={`glass-strong glass-edge overflow-hidden border ${
          isLlm ? 'border-accent-400/25' : 'border-white/10'
        }`}
      >
        <header className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 px-6 py-4">
          <div className="flex items-center gap-3">
            <span
              className={`flex h-9 w-9 items-center justify-center rounded-xl border ${
                isLlm
                  ? 'border-accent-400/30 bg-accent-500/12 shadow-glow-sm'
                  : 'border-white/10 bg-white/5'
              }`}
            >
              {isLlm ? (
                <Brain className="h-4.5 w-4.5 text-accent-300" strokeWidth={1.9} />
              ) : (
                <CircuitBoard className="h-4.5 w-4.5 text-slate-400" strokeWidth={1.9} />
              )}
            </span>
            <div>
              <h3 className="display-card-title">
                {isLlm ? 'AI Security Analysis' : 'Rule-Based Security Analysis'}
              </h3>
              <p className="mt-0.5 text-[11px] text-slate-500">
                {isLlm
                  ? `Generated by ${explanation.model}${
                      explanation.latency_ms ? ` in ${explanation.latency_ms} ms` : ''
                    }`
                  : 'Deterministic analysis derived from the extracted features'}
              </p>
            </div>
          </div>

          <span
            className={`badge ${
              isLlm
                ? 'border-accent-400/25 bg-accent-500/10 text-accent-200'
                : 'border-white/10 bg-white/5 text-slate-400'
            }`}
          >
            <Sparkles className="h-3 w-3" />
            {isLlm ? 'LLM + LangChain' : 'Fallback'}
          </span>
        </header>

        {explanation.notice && (
          <div className="flex items-start gap-2.5 border-b border-white/10 bg-caution/[0.07] px-6 py-3">
            <Info className="mt-0.5 h-4 w-4 shrink-0 text-caution" />
            <p className="text-[13px] leading-relaxed text-caution/90">{explanation.notice}</p>
          </div>
        )}

        <div className="space-y-4 px-6 py-6">
          {paragraphs.map((paragraph, index) => (
            <p key={index} className="text-[14px] leading-relaxed text-slate-300">
              {paragraph}
            </p>
          ))}
        </div>

        <footer className="border-t border-white/10 px-6 py-3">
          <p className="text-[11px] leading-relaxed text-slate-500">
            This explanation interprets the classifier&apos;s output and the characteristics
            extracted from the URL text. The site was not visited, and no WHOIS,
            DNS, certificate or reputation data was consulted.
          </p>
        </footer>
      </div>
    </section>
  )
}
